arch:
    - amd64
    - ppc64le
language: c

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          packages:
          - cmake
    - os: osx

script: cmake . && make && CTEST_OUTPUT_ON_FAILURE=on make test
