m4_include([ac_compile_check_sizeof.m4])
m4_include([ac_create_stdint_h.m4])
m4_include([ac_ptyranges.m4])
m4_include([ac_net.m4])
m4_include([ac_sol_ip.m4])
m4_include([ac_ucs_size.m4])
m4_include([ac_ai_addrconfig.m4])
m4_include([ac_easter_egg.m4])
