.TH ansi2html 1 2007-09-04 KBtin KBtin
.SH NAME
ansi2html \- ansi to HTML converter
.SH SYNOPSIS
.B ansi2html
<
.I log
>
.I outfile
.SH DESCRIPTION
.B ansi2html
will convert the ANSI log into a pretty HTML page, converting ANSI color
codes into HTML tags.  All standard colors and attributes are supported;
this does not include xterm-only extensions.
.P
Since version 1.0.10, ansi2html no longer tries to change blinking text into
something else.  On most browsers it will show properly, on Links, Internet
Explorer and possibly others it won't blink.
.SH CAVEATS
ANSI codes other than color codes are ignored; possibly causing misformatted
output.
.SH "SEE ALSO"
.BR ansi2txt ,
.BR ansi2html ,
.BR KBtin .
