.TH ansi2html 1 2018-05-27
.SH NAME
ansi2html \- ansi to HTML converter
.SH SYNOPSIS
.B ansi2html
.RB [ -nwctl ]
.BI < log
.BI > outfile
.SH DESCRIPTION
.B ansi2html
will convert the ANSI log into an HTML page, converting ANSI color codes into
appropriate tags.  All common colors and attributes are supported.
.SH OPTIONS
.TP
.BR -n ", " --no-header
Don't produce an HTML header.  This allows including the log into a web page
you make some other way.  You are responsible for setting background color
appropriately \(em to black or something dark in the default on-black mode,
or to white/light when \fB-w\fR is used.  Fancy-schmancy background images
are fine as long as they are dark (or light) enough.
.TP
.BR -w ", " --white
Make the background white.  This is contrary to most terminals but matches
most webpages.  Text requested to be bolded (normally bright white) will be
turned bold black, but explicit bright white \fIwill not\fR be changed,
becoming invisible (just like explicit black is invisible in the normal
on-black mode), same as on real terminals (see \fB-c\fR).
.TP
.BR -c ", " --contrast
Forbid invisible text.  Whenever foreground color is same as background,
it'll be turned halfway across the color space (so white and black become
gray).  This is inaccurate wrt real terminals, and most web users already
know how to mouse-highlight "spoiler" text, but can be useful if you
process logs that assume different white-vs-black background than you.
.TP
.BR -t ", " --title " \fItext\fR"
Set the page title to the next argument.  Mutually exclusive with
.BR -n .
.TP
.BR -l ", " --no-wrap
Disable word-wrapping.  Like text terminals, ansi2html wraps text by
default, which is contrary to the usual browser default for plain text.
.TP
.BR --style " \fItext\fR"
Injects some text into the stylesheet, obviously doesn't make any sense with
.BR -n .
Example:
.I --style 'pre {font-family: Consolas}'
.SH CAVEATS
Most ANSI codes other than color codes are ignored; possibly causing
misformatted output.  In general, anything unfit for a hardcopy terminal
won't work.
.SH "SEE ALSO"
.BR ansi2txt (1),
.BR ttyrec2ansi (1),
.BR pipetty (1).
