.TH ansi2txt 1 2002-09-02 KBtin KBtin
.SH NAME
ansi2txt \- ansi to plain text converter
.SH SYNOPSIS
.B ansi2txt
<
.I log
>
.I outfile
.SH DESCRIPTION
.B ansi2txt
can be used to convert text containing ANSI color codes (such as MUD logs,
text processed by syntax highlighters, colorgcc, colordiff, ccze, loco, etc)
into plain ASCII text.  It works as a filter, reading from stdin, removing
all ANSI codes and sending the output to stdout.
.SH CAVEATS
All ANSI codes are simply ignored, including all cursor positioning ones.
Sometimes this is what you want, sometimes it isn't.
.SH "SEE ALSO"
.BR ansi2html ,
.BR ttyrec2ansi ,
.BR KBtin .
