.TH KBtin 6 2002-09-02 KBtin KBtin
.SH NAME
KBtin \- a MUD client
.SH SYNOPSIS
.B KBtin
[
.B -v
] [
.I config_file
"... ]"
.SH DESCRIPTION
.I "Note: this man is just a stub, sort of a starter's guide.  For real docs, you will have to resort to the on-line help system."
.PP
blah
.SH "SEE ALSO"
.BR ansi2txt,
.BR ansi2html
- log converters.
