.TH KBtin 6 2007-09-04 KBtin KBtin
.SH NAME
KBtin \- a MUD client and an environment for line-based programs
.SH SYNOPSIS
.B KBtin
[
.I -v
] [
.I scriptfile
[
.I scriptfile2
\&... ]]
.SH DESCRIPTION
.B KBtin
is a MUD client based on the venerable
.B tintin++
; however it has uses beyond playing MUDs.
.br
A few commands (try #help for the full list):
.TP
.BI #session " " sesname " " hostname " " port
Starts a new session. The
.I sesname
is a nickname of the new session, and doesn't play any important role.
KBtin will open a telnet connection to the given
.I hostname
:
.IR port .
.TP
.BI #run " " sesname " " command
Starts a new session by running a local command.  In particular, you can
use it to start an encrypted connection by
.IR "#run foo ssh foo.bar.baz" .
.TP
.BI #help " " command
Gives you the help on
.IR command.
.TP
.B #verbatim
Disables all input parsing, making all text pass as-is.  Features such
as scrollback, highlights, logging, keybindings or actions continue to
work.
.TP
.B #end
Exits KBtin and returns you to your shell.
.SH OPTIONS
.TP
.B -v
Shows the processing done by all subsequent uses of
.IR #read .
Equivalent to
.IR "#verbose 1" .
.TP
.B -q
Turns off the output from
.IR #read .
Equivalent to
.IR "#verbose 0" .
.TP
.I "scriptname"
Processes the commands in
.IR scriptname ,
using
.IR "#read scriptname" .
.TP
.BI -c " " "command"
Executes a single command.  (Note: beware of the evil shell and escape
 '#'s!)
.TP
.BI -s " " "host" " " "port"
Starts a new session by opening a TELNET connection to the given host on the
given port.  KBtin will make up a session name for you.
.TP
.BI -S " " "host" " " "port"
Same, except that SSL encryption will be used.
.TP
.BI -r " " "shell_command"
Starts a new session by starting a local process.  The process will be opened
in a pseudo-terminal, making it interactive.  The session name will be made
up by KBtin.
.TP
.BI -p
Selects the "pipe" driver (default if stdin or stdout is not a terminal).
.TP
.BI -i
Selects the full interactive tty driver (usual default).
.SH "SEE ALSO"
.BR ansi2txt ,
.BR ansi2html .
