#!/bin/sh

DIR="$1"
shift
DIR="${*:+${DIR:-.}/}"

mkdir -p "protos"

for f in ${*:--}
  do
    h="${f%.c}.h"
    (cd "$DIR";
    egrep -h '^[a-zA-Z_]+.*[a-zA-Z_][a-zA-Z0-9_]*\(.*\)$' "$f"|
    grep -v '^static'|
    egrep -v '^void [a-z_]+_command\('|
    egrep -v '^struct session \*[a-z_]+_command\('|
    while read x
      do
        echo "$x;"
      done) >"protos/$h"
  done
