#define TRANSLIT_MIN 0x00A0
#define TRANSLIT_MAX 0x02EE
static char tlits[]=
{
/* U+00A0 */	' ',       	/* NO-BREAK SPACE */
/* U+00A1 */	'!',       	/* INVERTED EXCLAMATION MARK */
/* U+00A2 */	'c',       	/* CENT SIGN */
/* U+00A3 */	'L',       	/* POUND SIGN */
/* U+00A4 */	'$',       	/* CURRENCY SIGN */
/* U+00A5 */	'Y',       	/* YEN SIGN */
/* U+00A6 */	'|',       	/* BROKEN BAR */
/* U+00A7 */	'$',       	/* SECTION SIGN */
/* U+00A8 */	'"',       	/* DIAERESIS */
/* U+00A9 */	BAD_CHAR,  	/* COPYRIGHT SIGN */
/* U+00AA */	BAD_CHAR,  	/* FEMININE ORDINAL INDICATOR */
/* U+00AB */	'<',       	/* LEFT-POINTING DOUBLE ANGLE QUOTATION MARK */
/* U+00AC */	'!',       	/* NOT SIGN */
/* U+00AD */	'-',       	/* SOFT HYPHEN */
/* U+00AE */	BAD_CHAR,  	/* REGISTERED SIGN */
/* U+00AF */	'-',       	/* MACRON */
/* U+00B0 */	BAD_CHAR,  	/* DEGREE SIGN */
/* U+00B1 */	BAD_CHAR,  	/* PLUS-MINUS SIGN */
/* U+00B2 */	BAD_CHAR,  	/* SUPERSCRIPT TWO */
/* U+00B3 */	BAD_CHAR,  	/* SUPERSCRIPT THREE */
/* U+00B4 */	'\'',       	/* ACUTE ACCENT */
/* U+00B5 */	'u',       	/* MICRO SIGN */
/* U+00B6 */	BAD_CHAR,  	/* PILCROW SIGN */
/* U+00B7 */	'.',       	/* MIDDLE DOT */
/* U+00B8 */	',',       	/* CEDILLA */
/* U+00B9 */	BAD_CHAR,  	/* SUPERSCRIPT ONE */
/* U+00BA */	BAD_CHAR,  	/* MASCULINE ORDINAL INDICATOR */
/* U+00BB */	'>',       	/* RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK */
/* U+00BC */	BAD_CHAR,  	/* VULGAR FRACTION ONE QUARTER */
/* U+00BD */	BAD_CHAR,  	/* VULGAR FRACTION ONE HALF */
/* U+00BE */	BAD_CHAR,  	/* VULGAR FRACTION THREE QUARTERS */
/* U+00BF */	'?',       	/* INVERTED QUESTION MARK */
/* U+00C0 */	'A',       	/* LATIN CAPITAL LETTER A WITH GRAVE */
/* U+00C1 */	'A',       	/* LATIN CAPITAL LETTER A WITH ACUTE */
/* U+00C2 */	'A',       	/* LATIN CAPITAL LETTER A WITH CIRCUMFLEX */
/* U+00C3 */	'A',       	/* LATIN CAPITAL LETTER A WITH TILDE */
/* U+00C4 */	'A',       	/* LATIN CAPITAL LETTER A WITH DIAERESIS */
/* U+00C5 */	'A',       	/* LATIN CAPITAL LETTER A WITH RING ABOVE */
/* U+00C6 */	'A',       	/* LATIN CAPITAL LETTER AE */
/* U+00C7 */	'C',       	/* LATIN CAPITAL LETTER C WITH CEDILLA */
/* U+00C8 */	'E',       	/* LATIN CAPITAL LETTER E WITH GRAVE */
/* U+00C9 */	'E',       	/* LATIN CAPITAL LETTER E WITH ACUTE */
/* U+00CA */	'E',       	/* LATIN CAPITAL LETTER E WITH CIRCUMFLEX */
/* U+00CB */	'E',       	/* LATIN CAPITAL LETTER E WITH DIAERESIS */
/* U+00CC */	'I',       	/* LATIN CAPITAL LETTER I WITH GRAVE */
/* U+00CD */	'I',       	/* LATIN CAPITAL LETTER I WITH ACUTE */
/* U+00CE */	'I',       	/* LATIN CAPITAL LETTER I WITH CIRCUMFLEX */
/* U+00CF */	'I',       	/* LATIN CAPITAL LETTER I WITH DIAERESIS */
/* U+00D0 */	'D',       	/* LATIN CAPITAL LETTER ETH */
/* U+00D1 */	'N',       	/* LATIN CAPITAL LETTER N WITH TILDE */
/* U+00D2 */	'O',       	/* LATIN CAPITAL LETTER O WITH GRAVE */
/* U+00D3 */	'O',       	/* LATIN CAPITAL LETTER O WITH ACUTE */
/* U+00D4 */	'O',       	/* LATIN CAPITAL LETTER O WITH CIRCUMFLEX */
/* U+00D5 */	'O',       	/* LATIN CAPITAL LETTER O WITH TILDE */
/* U+00D6 */	'O',       	/* LATIN CAPITAL LETTER O WITH DIAERESIS */
/* U+00D7 */	'*',       	/* MULTIPLICATION SIGN */
/* U+00D8 */	'O',       	/* LATIN CAPITAL LETTER O WITH STROKE */
/* U+00D9 */	'U',       	/* LATIN CAPITAL LETTER U WITH GRAVE */
/* U+00DA */	'U',       	/* LATIN CAPITAL LETTER U WITH ACUTE */
/* U+00DB */	'U',       	/* LATIN CAPITAL LETTER U WITH CIRCUMFLEX */
/* U+00DC */	'U',       	/* LATIN CAPITAL LETTER U WITH DIAERESIS */
/* U+00DD */	'Y',       	/* LATIN CAPITAL LETTER Y WITH ACUTE */
/* U+00DE */	'T',       	/* LATIN CAPITAL LETTER THORN */
/* U+00DF */	's',       	/* LATIN SMALL LETTER SHARP S */
/* U+00E0 */	'a',       	/* LATIN SMALL LETTER A WITH GRAVE */
/* U+00E1 */	'a',       	/* LATIN SMALL LETTER A WITH ACUTE */
/* U+00E2 */	'a',       	/* LATIN SMALL LETTER A WITH CIRCUMFLEX */
/* U+00E3 */	'a',       	/* LATIN SMALL LETTER A WITH TILDE */
/* U+00E4 */	'a',       	/* LATIN SMALL LETTER A WITH DIAERESIS */
/* U+00E5 */	'a',       	/* LATIN SMALL LETTER A WITH RING ABOVE */
/* U+00E6 */	'a',       	/* LATIN SMALL LETTER AE */
/* U+00E7 */	'c',       	/* LATIN SMALL LETTER C WITH CEDILLA */
/* U+00E8 */	'e',       	/* LATIN SMALL LETTER E WITH GRAVE */
/* U+00E9 */	'e',       	/* LATIN SMALL LETTER E WITH ACUTE */
/* U+00EA */	'e',       	/* LATIN SMALL LETTER E WITH CIRCUMFLEX */
/* U+00EB */	'e',       	/* LATIN SMALL LETTER E WITH DIAERESIS */
/* U+00EC */	'i',       	/* LATIN SMALL LETTER I WITH GRAVE */
/* U+00ED */	'i',       	/* LATIN SMALL LETTER I WITH ACUTE */
/* U+00EE */	'i',       	/* LATIN SMALL LETTER I WITH CIRCUMFLEX */
/* U+00EF */	'i',       	/* LATIN SMALL LETTER I WITH DIAERESIS */
/* U+00F0 */	'd',       	/* LATIN SMALL LETTER ETH */
/* U+00F1 */	'n',       	/* LATIN SMALL LETTER N WITH TILDE */
/* U+00F2 */	'o',       	/* LATIN SMALL LETTER O WITH GRAVE */
/* U+00F3 */	'o',       	/* LATIN SMALL LETTER O WITH ACUTE */
/* U+00F4 */	'o',       	/* LATIN SMALL LETTER O WITH CIRCUMFLEX */
/* U+00F5 */	'o',       	/* LATIN SMALL LETTER O WITH TILDE */
/* U+00F6 */	'o',       	/* LATIN SMALL LETTER O WITH DIAERESIS */
/* U+00F7 */	'/',       	/* DIVISION SIGN */
/* U+00F8 */	'o',       	/* LATIN SMALL LETTER O WITH STROKE */
/* U+00F9 */	'u',       	/* LATIN SMALL LETTER U WITH GRAVE */
/* U+00FA */	'u',       	/* LATIN SMALL LETTER U WITH ACUTE */
/* U+00FB */	'u',       	/* LATIN SMALL LETTER U WITH CIRCUMFLEX */
/* U+00FC */	'u',       	/* LATIN SMALL LETTER U WITH DIAERESIS */
/* U+00FD */	'y',       	/* LATIN SMALL LETTER Y WITH ACUTE */
/* U+00FE */	't',       	/* LATIN SMALL LETTER THORN */
/* U+00FF */	'y',       	/* LATIN SMALL LETTER Y WITH DIAERESIS */
/* U+0100 */	'A',       	/* LATIN CAPITAL LETTER A WITH MACRON */
/* U+0101 */	'a',       	/* LATIN SMALL LETTER A WITH MACRON */
/* U+0102 */	'A',       	/* LATIN CAPITAL LETTER A WITH BREVE */
/* U+0103 */	'a',       	/* LATIN SMALL LETTER A WITH BREVE */
/* U+0104 */	'A',       	/* LATIN CAPITAL LETTER A WITH OGONEK */
/* U+0105 */	'a',       	/* LATIN SMALL LETTER A WITH OGONEK */
/* U+0106 */	'C',       	/* LATIN CAPITAL LETTER C WITH ACUTE */
/* U+0107 */	'c',       	/* LATIN SMALL LETTER C WITH ACUTE */
/* U+0108 */	'C',       	/* LATIN CAPITAL LETTER C WITH CIRCUMFLEX */
/* U+0109 */	'c',       	/* LATIN SMALL LETTER C WITH CIRCUMFLEX */
/* U+010A */	'C',       	/* LATIN CAPITAL LETTER C WITH DOT ABOVE */
/* U+010B */	'c',       	/* LATIN SMALL LETTER C WITH DOT ABOVE */
/* U+010C */	'C',       	/* LATIN CAPITAL LETTER C WITH CARON */
/* U+010D */	'c',       	/* LATIN SMALL LETTER C WITH CARON */
/* U+010E */	'D',       	/* LATIN CAPITAL LETTER D WITH CARON */
/* U+010F */	'd',       	/* LATIN SMALL LETTER D WITH CARON */
/* U+0110 */	'D',       	/* LATIN CAPITAL LETTER D WITH STROKE */
/* U+0111 */	'd',       	/* LATIN SMALL LETTER D WITH STROKE */
/* U+0112 */	'E',       	/* LATIN CAPITAL LETTER E WITH MACRON */
/* U+0113 */	'e',       	/* LATIN SMALL LETTER E WITH MACRON */
/* U+0114 */	'E',       	/* LATIN CAPITAL LETTER E WITH BREVE */
/* U+0115 */	'e',       	/* LATIN SMALL LETTER E WITH BREVE */
/* U+0116 */	'E',       	/* LATIN CAPITAL LETTER E WITH DOT ABOVE */
/* U+0117 */	'e',       	/* LATIN SMALL LETTER E WITH DOT ABOVE */
/* U+0118 */	'E',       	/* LATIN CAPITAL LETTER E WITH OGONEK */
/* U+0119 */	'e',       	/* LATIN SMALL LETTER E WITH OGONEK */
/* U+011A */	'E',       	/* LATIN CAPITAL LETTER E WITH CARON */
/* U+011B */	'e',       	/* LATIN SMALL LETTER E WITH CARON */
/* U+011C */	'G',       	/* LATIN CAPITAL LETTER G WITH CIRCUMFLEX */
/* U+011D */	'g',       	/* LATIN SMALL LETTER G WITH CIRCUMFLEX */
/* U+011E */	'G',       	/* LATIN CAPITAL LETTER G WITH BREVE */
/* U+011F */	'g',       	/* LATIN SMALL LETTER G WITH BREVE */
/* U+0120 */	'G',       	/* LATIN CAPITAL LETTER G WITH DOT ABOVE */
/* U+0121 */	'g',       	/* LATIN SMALL LETTER G WITH DOT ABOVE */
/* U+0122 */	'G',       	/* LATIN CAPITAL LETTER G WITH CEDILLA */
/* U+0123 */	'g',       	/* LATIN SMALL LETTER G WITH CEDILLA */
/* U+0124 */	'H',       	/* LATIN CAPITAL LETTER H WITH CIRCUMFLEX */
/* U+0125 */	'h',       	/* LATIN SMALL LETTER H WITH CIRCUMFLEX */
/* U+0126 */	'H',       	/* LATIN CAPITAL LETTER H WITH STROKE */
/* U+0127 */	'h',       	/* LATIN SMALL LETTER H WITH STROKE */
/* U+0128 */	'I',       	/* LATIN CAPITAL LETTER I WITH TILDE */
/* U+0129 */	'i',       	/* LATIN SMALL LETTER I WITH TILDE */
/* U+012A */	'I',       	/* LATIN CAPITAL LETTER I WITH MACRON */
/* U+012B */	'i',       	/* LATIN SMALL LETTER I WITH MACRON */
/* U+012C */	'I',       	/* LATIN CAPITAL LETTER I WITH BREVE */
/* U+012D */	'i',       	/* LATIN SMALL LETTER I WITH BREVE */
/* U+012E */	'I',       	/* LATIN CAPITAL LETTER I WITH OGONEK */
/* U+012F */	'i',       	/* LATIN SMALL LETTER I WITH OGONEK */
/* U+0130 */	'I',       	/* LATIN CAPITAL LETTER I WITH DOT ABOVE */
/* U+0131 */	'i',       	/* LATIN SMALL LETTER DOTLESS I */
/* U+0132 */	BAD_CHAR,  	/* LATIN CAPITAL LIGATURE IJ */
/* U+0133 */	BAD_CHAR,  	/* LATIN SMALL LIGATURE IJ */
/* U+0134 */	'J',       	/* LATIN CAPITAL LETTER J WITH CIRCUMFLEX */
/* U+0135 */	'j',       	/* LATIN SMALL LETTER J WITH CIRCUMFLEX */
/* U+0136 */	'K',       	/* LATIN CAPITAL LETTER K WITH CEDILLA */
/* U+0137 */	'k',       	/* LATIN SMALL LETTER K WITH CEDILLA */
/* U+0138 */	'k',       	/* LATIN SMALL LETTER KRA */
/* U+0139 */	'K',       	/* LATIN CAPITAL LETTER L WITH ACUTE */
/* U+013A */	'l',       	/* LATIN SMALL LETTER L WITH ACUTE */
/* U+013B */	'L',       	/* LATIN CAPITAL LETTER L WITH CEDILLA */
/* U+013C */	'l',       	/* LATIN SMALL LETTER L WITH CEDILLA */
/* U+013D */	'L',       	/* LATIN CAPITAL LETTER L WITH CARON */
/* U+013E */	'l',       	/* LATIN SMALL LETTER L WITH CARON */
/* U+013F */	'L',       	/* LATIN CAPITAL LETTER L WITH MIDDLE DOT */
/* U+0140 */	'l',       	/* LATIN SMALL LETTER L WITH MIDDLE DOT */
/* U+0141 */	'L',       	/* LATIN CAPITAL LETTER L WITH STROKE */
/* U+0142 */	'l',       	/* LATIN SMALL LETTER L WITH STROKE */
/* U+0143 */	'N',       	/* LATIN CAPITAL LETTER N WITH ACUTE */
/* U+0144 */	'n',       	/* LATIN SMALL LETTER N WITH ACUTE */
/* U+0145 */	'N',       	/* LATIN CAPITAL LETTER N WITH CEDILLA */
/* U+0146 */	'n',       	/* LATIN SMALL LETTER N WITH CEDILLA */
/* U+0147 */	'N',       	/* LATIN CAPITAL LETTER N WITH CARON */
/* U+0148 */	'n',       	/* LATIN SMALL LETTER N WITH CARON */
/* U+0149 */	'n',       	/* LATIN SMALL LETTER N PRECEDED BY APOSTROPHE */
/* U+014A */	'N',       	/* LATIN CAPITAL LETTER ENG */
/* U+014B */	'n',       	/* LATIN SMALL LETTER ENG */
/* U+014C */	'O',       	/* LATIN CAPITAL LETTER O WITH MACRON */
/* U+014D */	'o',       	/* LATIN SMALL LETTER O WITH MACRON */
/* U+014E */	'O',       	/* LATIN CAPITAL LETTER O WITH BREVE */
/* U+014F */	'o',       	/* LATIN SMALL LETTER O WITH BREVE */
/* U+0150 */	'O',       	/* LATIN CAPITAL LETTER O WITH DOUBLE ACUTE */
/* U+0151 */	'o',       	/* LATIN SMALL LETTER O WITH DOUBLE ACUTE */
/* U+0152 */	'O',       	/* LATIN CAPITAL LIGATURE OE */
/* U+0153 */	'o',       	/* LATIN SMALL LIGATURE OE */
/* U+0154 */	'R',       	/* LATIN CAPITAL LETTER R WITH ACUTE */
/* U+0155 */	'r',       	/* LATIN SMALL LETTER R WITH ACUTE */
/* U+0156 */	'R',       	/* LATIN CAPITAL LETTER R WITH CEDILLA */
/* U+0157 */	'r',       	/* LATIN SMALL LETTER R WITH CEDILLA */
/* U+0158 */	'R',       	/* LATIN CAPITAL LETTER R WITH CARON */
/* U+0159 */	'r',       	/* LATIN SMALL LETTER R WITH CARON */
/* U+015A */	'S',       	/* LATIN CAPITAL LETTER S WITH ACUTE */
/* U+015B */	's',       	/* LATIN SMALL LETTER S WITH ACUTE */
/* U+015C */	'S',       	/* LATIN CAPITAL LETTER S WITH CIRCUMFLEX */
/* U+015D */	's',       	/* LATIN SMALL LETTER S WITH CIRCUMFLEX */
/* U+015E */	'S',       	/* LATIN CAPITAL LETTER S WITH CEDILLA */
/* U+015F */	's',       	/* LATIN SMALL LETTER S WITH CEDILLA */
/* U+0160 */	'S',       	/* LATIN CAPITAL LETTER S WITH CARON */
/* U+0161 */	's',       	/* LATIN SMALL LETTER S WITH CARON */
/* U+0162 */	'T',       	/* LATIN CAPITAL LETTER T WITH CEDILLA */
/* U+0163 */	't',       	/* LATIN SMALL LETTER T WITH CEDILLA */
/* U+0164 */	'T',       	/* LATIN CAPITAL LETTER T WITH CARON */
/* U+0165 */	't',       	/* LATIN SMALL LETTER T WITH CARON */
/* U+0166 */	'T',       	/* LATIN CAPITAL LETTER T WITH STROKE */
/* U+0167 */	't',       	/* LATIN SMALL LETTER T WITH STROKE */
/* U+0168 */	'U',       	/* LATIN CAPITAL LETTER U WITH TILDE */
/* U+0169 */	'u',       	/* LATIN SMALL LETTER U WITH TILDE */
/* U+016A */	'U',       	/* LATIN CAPITAL LETTER U WITH MACRON */
/* U+016B */	'u',       	/* LATIN SMALL LETTER U WITH MACRON */
/* U+016C */	'U',       	/* LATIN CAPITAL LETTER U WITH BREVE */
/* U+016D */	'u',       	/* LATIN SMALL LETTER U WITH BREVE */
/* U+016E */	'U',       	/* LATIN CAPITAL LETTER U WITH RING ABOVE */
/* U+016F */	'u',       	/* LATIN SMALL LETTER U WITH RING ABOVE */
/* U+0170 */	'U',       	/* LATIN CAPITAL LETTER U WITH DOUBLE ACUTE */
/* U+0171 */	'u',       	/* LATIN SMALL LETTER U WITH DOUBLE ACUTE */
/* U+0172 */	'U',       	/* LATIN CAPITAL LETTER U WITH OGONEK */
/* U+0173 */	'u',       	/* LATIN SMALL LETTER U WITH OGONEK */
/* U+0174 */	'W',       	/* LATIN CAPITAL LETTER W WITH CIRCUMFLEX */
/* U+0175 */	'w',       	/* LATIN SMALL LETTER W WITH CIRCUMFLEX */
/* U+0176 */	'Y',       	/* LATIN CAPITAL LETTER Y WITH CIRCUMFLEX */
/* U+0177 */	'y',       	/* LATIN SMALL LETTER Y WITH CIRCUMFLEX */
/* U+0178 */	'Y',       	/* LATIN CAPITAL LETTER Y WITH DIAERESIS */
/* U+0179 */	'Z',       	/* LATIN CAPITAL LETTER Z WITH ACUTE */
/* U+017A */	'z',       	/* LATIN SMALL LETTER Z WITH ACUTE */
/* U+017B */	'Z',       	/* LATIN CAPITAL LETTER Z WITH DOT ABOVE */
/* U+017C */	'z',       	/* LATIN SMALL LETTER Z WITH DOT ABOVE */
/* U+017D */	'Z',       	/* LATIN CAPITAL LETTER Z WITH CARON */
/* U+017E */	'z',       	/* LATIN SMALL LETTER Z WITH CARON */
/* U+017F */	's',       	/* LATIN SMALL LETTER LONG S */
/* U+0180 */	'b',       	/* LATIN SMALL LETTER B WITH STROKE */
/* U+0181 */	'B',       	/* LATIN CAPITAL LETTER B WITH HOOK */
/* U+0182 */	'B',       	/* LATIN CAPITAL LETTER B WITH TOPBAR */
/* U+0183 */	'b',       	/* LATIN SMALL LETTER B WITH TOPBAR */
/* U+0184 */	'6',       	/* LATIN CAPITAL LETTER TONE SIX */
/* U+0185 */	'6',       	/* LATIN SMALL LETTER TONE SIX */
/* U+0186 */	'O',       	/* LATIN CAPITAL LETTER OPEN O */
/* U+0187 */	'C',       	/* LATIN CAPITAL LETTER C WITH HOOK */
/* U+0188 */	'C',       	/* LATIN SMALL LETTER C WITH HOOK */
/* U+0189 */	'D',       	/* LATIN CAPITAL LETTER AFRICAN D */
/* U+018A */	'D',       	/* LATIN CAPITAL LETTER D WITH HOOK */
/* U+018B */	'D',       	/* LATIN CAPITAL LETTER D WITH TOPBAR */
/* U+018C */	'd',       	/* LATIN SMALL LETTER D WITH TOPBAR */
/* U+018D */	'd',       	/* LATIN SMALL LETTER TURNED DELTA */
/* U+018E */	'E',       	/* LATIN CAPITAL LETTER REVERSED E */
/* U+018F */	'E',       	/* LATIN CAPITAL LETTER SCHWA */
/* U+0190 */	'E',       	/* LATIN CAPITAL LETTER OPEN E */
/* U+0191 */	'F',       	/* LATIN CAPITAL LETTER F WITH HOOK */
/* U+0192 */	'f',       	/* LATIN SMALL LETTER F WITH HOOK */
/* U+0193 */	'G',       	/* LATIN CAPITAL LETTER G WITH HOOK */
/* U+0194 */	'G',       	/* LATIN CAPITAL LETTER GAMMA */
/* U+0195 */	'h',       	/* LATIN SMALL LETTER HV */
/* U+0196 */	'i',       	/* LATIN CAPITAL LETTER IOTA */
/* U+0197 */	'I',       	/* LATIN CAPITAL LETTER I WITH STROKE */
/* U+0198 */	'K',       	/* LATIN CAPITAL LETTER K WITH HOOK */
/* U+0199 */	'k',       	/* LATIN SMALL LETTER K WITH HOOK */
/* U+019A */	'l',       	/* LATIN SMALL LETTER L WITH BAR */
/* U+019B */	'l',       	/* LATIN SMALL LETTER LAMBDA WITH STROKE */
/* U+019C */	'M',       	/* LATIN CAPITAL LETTER TURNED M */
/* U+019D */	'N',       	/* LATIN CAPITAL LETTER N WITH LEFT HOOK */
/* U+019E */	'n',       	/* LATIN SMALL LETTER N WITH LONG RIGHT LEG */
/* U+019F */	'O',       	/* LATIN CAPITAL LETTER O WITH MIDDLE TILDE */
/* U+01A0 */	'O',       	/* LATIN CAPITAL LETTER O WITH HORN */
/* U+01A1 */	'o',       	/* LATIN SMALL LETTER O WITH HORN */
/* U+01A2 */	'O',       	/* LATIN CAPITAL LETTER OI */
/* U+01A3 */	'o',       	/* LATIN SMALL LETTER OI */
/* U+01A4 */	'P',       	/* LATIN CAPITAL LETTER P WITH HOOK */
/* U+01A5 */	'p',       	/* LATIN SMALL LETTER P WITH HOOK */
/* U+01A6 */	'k',       	/* LATIN LETTER YR */
/* U+01A7 */	'S',       	/* LATIN CAPITAL LETTER TONE TWO */
/* U+01A8 */	's',       	/* LATIN SMALL LETTER TONE TWO */
/* U+01A9 */	'E',       	/* LATIN CAPITAL LETTER ESH */
/* U+01AA */	'e',       	/* LATIN LETTER REVERSED ESH LOOP */
/* U+01AB */	't',       	/* LATIN SMALL LETTER T WITH PALATAL HOOK */
/* U+01AC */	'T',       	/* LATIN CAPITAL LETTER T WITH HOOK */
/* U+01AD */	't',       	/* LATIN SMALL LETTER T WITH HOOK */
/* U+01AE */	'T',       	/* LATIN CAPITAL LETTER T WITH RETROFLEX HOOK */
/* U+01AF */	'U',       	/* LATIN CAPITAL LETTER U WITH HORN */
/* U+01B0 */	'u',       	/* LATIN SMALL LETTER U WITH HORN */
/* U+01B1 */	'U',       	/* LATIN CAPITAL LETTER UPSILON */
/* U+01B2 */	'V',       	/* LATIN CAPITAL LETTER V WITH HOOK */
/* U+01B3 */	'Y',       	/* LATIN CAPITAL LETTER Y WITH HOOK */
/* U+01B4 */	'y',       	/* LATIN SMALL LETTER Y WITH HOOK */
/* U+01B5 */	'Z',       	/* LATIN CAPITAL LETTER Z WITH STROKE */
/* U+01B6 */	'z',       	/* LATIN SMALL LETTER Z WITH STROKE */
/* U+01B7 */	'E',       	/* LATIN CAPITAL LETTER EZH */
/* U+01B8 */	'e',       	/* LATIN CAPITAL LETTER EZH REVERSED */
/* U+01B9 */	'e',       	/* LATIN SMALL LETTER EZH REVERSED */
/* U+01BA */	'e',       	/* LATIN SMALL LETTER EZH WITH TAIL */
/* U+01BB */	'2',       	/* LATIN LETTER TWO WITH STROKE */
/* U+01BC */	'5',       	/* LATIN CAPITAL LETTER TONE FIVE */
/* U+01BD */	'5',       	/* LATIN SMALL LETTER TONE FIVE */
/* U+01BE */	's',       	/* LATIN LETTER INVERTED GLOTTAL STOP WITH STROKE */
/* U+01BF */	'p',       	/* LATIN LETTER WYNN */
/* U+01C0 */	BAD_CHAR,  	/* LATIN LETTER DENTAL CLICK */
/* U+01C1 */	BAD_CHAR,  	/* LATIN LETTER LATERAL CLICK */
/* U+01C2 */	BAD_CHAR,  	/* LATIN LETTER ALVEOLAR CLICK */
/* U+01C3 */	BAD_CHAR,  	/* LATIN LETTER RETROFLEX CLICK */
/* U+01C4 */	BAD_CHAR,  	/* LATIN CAPITAL LETTER DZ WITH CARON */
/* U+01C5 */	BAD_CHAR,  	/* LATIN CAPITAL LETTER D WITH SMALL LETTER Z WITH CARON */
/* U+01C6 */	BAD_CHAR,  	/* LATIN SMALL LETTER DZ WITH CARON */
/* U+01C7 */	BAD_CHAR,  	/* LATIN CAPITAL LETTER LJ */
/* U+01C8 */	BAD_CHAR,  	/* LATIN CAPITAL LETTER L WITH SMALL LETTER J */
/* U+01C9 */	BAD_CHAR,  	/* LATIN SMALL LETTER LJ */
/* U+01CA */	BAD_CHAR,  	/* LATIN CAPITAL LETTER NJ */
/* U+01CB */	BAD_CHAR,  	/* LATIN CAPITAL LETTER N WITH SMALL LETTER J */
/* U+01CC */	BAD_CHAR,  	/* LATIN SMALL LETTER NJ */
/* U+01CD */	'A',       	/* LATIN CAPITAL LETTER A WITH CARON */
/* U+01CE */	'a',       	/* LATIN SMALL LETTER A WITH CARON */
/* U+01CF */	'I',       	/* LATIN CAPITAL LETTER I WITH CARON */
/* U+01D0 */	'i',       	/* LATIN SMALL LETTER I WITH CARON */
/* U+01D1 */	'O',       	/* LATIN CAPITAL LETTER O WITH CARON */
/* U+01D2 */	'o',       	/* LATIN SMALL LETTER O WITH CARON */
/* U+01D3 */	'U',       	/* LATIN CAPITAL LETTER U WITH CARON */
/* U+01D4 */	'u',       	/* LATIN SMALL LETTER U WITH CARON */
/* U+01D5 */	'U',       	/* LATIN CAPITAL LETTER U WITH DIAERESIS AND MACRON */
/* U+01D6 */	'u',       	/* LATIN SMALL LETTER U WITH DIAERESIS AND MACRON */
/* U+01D7 */	'U',       	/* LATIN CAPITAL LETTER U WITH DIAERESIS AND ACUTE */
/* U+01D8 */	'u',       	/* LATIN SMALL LETTER U WITH DIAERESIS AND ACUTE */
/* U+01D9 */	'U',       	/* LATIN CAPITAL LETTER U WITH DIAERESIS AND CARON */
/* U+01DA */	'u',       	/* LATIN SMALL LETTER U WITH DIAERESIS AND CARON */
/* U+01DB */	'U',       	/* LATIN CAPITAL LETTER U WITH DIAERESIS AND GRAVE */
/* U+01DC */	'u',       	/* LATIN SMALL LETTER U WITH DIAERESIS AND GRAVE */
/* U+01DD */	'e',       	/* LATIN SMALL LETTER TURNED E */
/* U+01DE */	'A',       	/* LATIN CAPITAL LETTER A WITH DIAERESIS AND MACRON */
/* U+01DF */	'a',       	/* LATIN SMALL LETTER A WITH DIAERESIS AND MACRON */
/* U+01E0 */	'A',       	/* LATIN CAPITAL LETTER A WITH DOT ABOVE AND MACRON */
/* U+01E1 */	'a',       	/* LATIN SMALL LETTER A WITH DOT ABOVE AND MACRON */
/* U+01E2 */	'A',       	/* LATIN CAPITAL LETTER AE WITH MACRON */
/* U+01E3 */	'a',       	/* LATIN SMALL LETTER AE WITH MACRON */
/* U+01E4 */	'G',       	/* LATIN CAPITAL LETTER G WITH STROKE */
/* U+01E5 */	'g',       	/* LATIN SMALL LETTER G WITH STROKE */
/* U+01E6 */	'G',       	/* LATIN CAPITAL LETTER G WITH CARON */
/* U+01E7 */	'g',       	/* LATIN SMALL LETTER G WITH CARON */
/* U+01E8 */	'K',       	/* LATIN CAPITAL LETTER K WITH CARON */
/* U+01E9 */	'k',       	/* LATIN SMALL LETTER K WITH CARON */
/* U+01EA */	'O',       	/* LATIN CAPITAL LETTER O WITH OGONEK */
/* U+01EB */	'o',       	/* LATIN SMALL LETTER O WITH OGONEK */
/* U+01EC */	'O',       	/* LATIN CAPITAL LETTER O WITH OGONEK AND MACRON */
/* U+01ED */	'o',       	/* LATIN SMALL LETTER O WITH OGONEK AND MACRON */
/* U+01EE */	'E',       	/* LATIN CAPITAL LETTER EZH WITH CARON */
/* U+01EF */	'e',       	/* LATIN SMALL LETTER EZH WITH CARON */
/* U+01F0 */	'j',       	/* LATIN SMALL LETTER J WITH CARON */
/* U+01F1 */	BAD_CHAR,  	/* LATIN CAPITAL LETTER DZ */
/* U+01F2 */	BAD_CHAR,  	/* LATIN CAPITAL LETTER D WITH SMALL LETTER Z */
/* U+01F3 */	BAD_CHAR,  	/* LATIN SMALL LETTER DZ */
/* U+01F4 */	'G',       	/* LATIN CAPITAL LETTER G WITH ACUTE */
/* U+01F5 */	'g',       	/* LATIN SMALL LETTER G WITH ACUTE */
/* U+01F6 */	'H',       	/* LATIN CAPITAL LETTER HWAIR */
/* U+01F7 */	'P',       	/* LATIN CAPITAL LETTER WYNN */
/* U+01F8 */	'N',       	/* LATIN CAPITAL LETTER N WITH GRAVE */
/* U+01F9 */	'n',       	/* LATIN SMALL LETTER N WITH GRAVE */
/* U+01FA */	'A',       	/* LATIN CAPITAL LETTER A WITH RING ABOVE AND ACUTE */
/* U+01FB */	'a',       	/* LATIN SMALL LETTER A WITH RING ABOVE AND ACUTE */
/* U+01FC */	'A',       	/* LATIN CAPITAL LETTER AE WITH ACUTE */
/* U+01FD */	'a',       	/* LATIN SMALL LETTER AE WITH ACUTE */
/* U+01FE */	'O',       	/* LATIN CAPITAL LETTER O WITH STROKE AND ACUTE */
/* U+01FF */	'o',       	/* LATIN SMALL LETTER O WITH STROKE AND ACUTE */
/* U+0200 */	'A',       	/* LATIN CAPITAL LETTER A WITH DOUBLE GRAVE */
/* U+0201 */	'a',       	/* LATIN SMALL LETTER A WITH DOUBLE GRAVE */
/* U+0202 */	'A',       	/* LATIN CAPITAL LETTER A WITH INVERTED BREVE */
/* U+0203 */	'a',       	/* LATIN SMALL LETTER A WITH INVERTED BREVE */
/* U+0204 */	'E',       	/* LATIN CAPITAL LETTER E WITH DOUBLE GRAVE */
/* U+0205 */	'e',       	/* LATIN SMALL LETTER E WITH DOUBLE GRAVE */
/* U+0206 */	'E',       	/* LATIN CAPITAL LETTER E WITH INVERTED BREVE */
/* U+0207 */	'e',       	/* LATIN SMALL LETTER E WITH INVERTED BREVE */
/* U+0208 */	'I',       	/* LATIN CAPITAL LETTER I WITH DOUBLE GRAVE */
/* U+0209 */	'i',       	/* LATIN SMALL LETTER I WITH DOUBLE GRAVE */
/* U+020A */	'I',       	/* LATIN CAPITAL LETTER I WITH INVERTED BREVE */
/* U+020B */	'i',       	/* LATIN SMALL LETTER I WITH INVERTED BREVE */
/* U+020C */	'O',       	/* LATIN CAPITAL LETTER O WITH DOUBLE GRAVE */
/* U+020D */	'o',       	/* LATIN SMALL LETTER O WITH DOUBLE GRAVE */
/* U+020E */	'O',       	/* LATIN CAPITAL LETTER O WITH INVERTED BREVE */
/* U+020F */	'o',       	/* LATIN SMALL LETTER O WITH INVERTED BREVE */
/* U+0210 */	'R',       	/* LATIN CAPITAL LETTER R WITH DOUBLE GRAVE */
/* U+0211 */	'r',       	/* LATIN SMALL LETTER R WITH DOUBLE GRAVE */
/* U+0212 */	'R',       	/* LATIN CAPITAL LETTER R WITH INVERTED BREVE */
/* U+0213 */	'r',       	/* LATIN SMALL LETTER R WITH INVERTED BREVE */
/* U+0214 */	'U',       	/* LATIN CAPITAL LETTER U WITH DOUBLE GRAVE */
/* U+0215 */	'u',       	/* LATIN SMALL LETTER U WITH DOUBLE GRAVE */
/* U+0216 */	'U',       	/* LATIN CAPITAL LETTER U WITH INVERTED BREVE */
/* U+0217 */	'u',       	/* LATIN SMALL LETTER U WITH INVERTED BREVE */
/* U+0218 */	'S',       	/* LATIN CAPITAL LETTER S WITH COMMA BELOW */
/* U+0219 */	's',       	/* LATIN SMALL LETTER S WITH COMMA BELOW */
/* U+021A */	'T',       	/* LATIN CAPITAL LETTER T WITH COMMA BELOW */
/* U+021B */	't',       	/* LATIN SMALL LETTER T WITH COMMA BELOW */
/* U+021C */	'3',       	/* LATIN CAPITAL LETTER YOGH */
/* U+021D */	'3',       	/* LATIN SMALL LETTER YOGH */
/* U+021E */	'H',       	/* LATIN CAPITAL LETTER H WITH CARON */
/* U+021F */	'h',       	/* LATIN SMALL LETTER H WITH CARON */
/* U+0220 */	'N',       	/* LATIN CAPITAL LETTER N WITH LONG RIGHT LEG */
/* U+0221 */	'd',       	/* LATIN SMALL LETTER D WITH CURL */
/* U+0222 */	BAD_CHAR,  	/* LATIN CAPITAL LETTER OU */
/* U+0223 */	BAD_CHAR,  	/* LATIN SMALL LETTER OU */
/* U+0224 */	'Z',       	/* LATIN CAPITAL LETTER Z WITH HOOK */
/* U+0225 */	'z',       	/* LATIN SMALL LETTER Z WITH HOOK */
/* U+0226 */	'A',       	/* LATIN CAPITAL LETTER A WITH DOT ABOVE */
/* U+0227 */	'a',       	/* LATIN SMALL LETTER A WITH DOT ABOVE */
/* U+0228 */	'E',       	/* LATIN CAPITAL LETTER E WITH CEDILLA */
/* U+0229 */	'e',       	/* LATIN SMALL LETTER E WITH CEDILLA */
/* U+022A */	'O',       	/* LATIN CAPITAL LETTER O WITH DIAERESIS AND MACRON */
/* U+022B */	'o',       	/* LATIN SMALL LETTER O WITH DIAERESIS AND MACRON */
/* U+022C */	'O',       	/* LATIN CAPITAL LETTER O WITH TILDE AND MACRON */
/* U+022D */	'o',       	/* LATIN SMALL LETTER O WITH TILDE AND MACRON */
/* U+022E */	'O',       	/* LATIN CAPITAL LETTER O WITH DOT ABOVE */
/* U+022F */	'o',       	/* LATIN SMALL LETTER O WITH DOT ABOVE */
/* U+0230 */	'O',       	/* LATIN CAPITAL LETTER O WITH DOT ABOVE AND MACRON */
/* U+0231 */	'o',       	/* LATIN SMALL LETTER O WITH DOT ABOVE AND MACRON */
/* U+0232 */	'Y',       	/* LATIN CAPITAL LETTER Y WITH MACRON */
/* U+0233 */	'y',       	/* LATIN SMALL LETTER Y WITH MACRON */
/* U+0234 */	'l',       	/* LATIN SMALL LETTER L WITH CURL */
/* U+0235 */	'n',       	/* LATIN SMALL LETTER N WITH CURL */
/* U+0236 */	't',       	/* LATIN SMALL LETTER T WITH CURL */
/* U+0237 */	BAD_CHAR,  	/* LATIN SMALL LETTER DOTLESS J */
/* U+0238 */	BAD_CHAR,  	/* LATIN SMALL LETTER DB DIGRAPH */
/* U+0239 */	BAD_CHAR,  	/* LATIN SMALL LETTER QP DIGRAPH */
/* U+023A */	BAD_CHAR,  	/* LATIN CAPITAL LETTER A WITH STROKE */
/* U+023B */	BAD_CHAR,  	/* LATIN CAPITAL LETTER C WITH STROKE */
/* U+023C */	BAD_CHAR,  	/* LATIN SMALL LETTER C WITH STROKE */
/* U+023D */	BAD_CHAR,  	/* LATIN CAPITAL LETTER L WITH BAR */
/* U+023E */	BAD_CHAR,  	/* LATIN CAPITAL LETTER T WITH DIAGONAL STROKE */
/* U+023F */	BAD_CHAR,  	/* LATIN SMALL LETTER S WITH SWASH TAIL */
/* U+0240 */	BAD_CHAR,  	/* LATIN SMALL LETTER Z WITH SWASH TAIL */
/* U+0241 */	BAD_CHAR,  	/* LATIN CAPITAL LETTER GLOTTAL STOP */
/* U+0242 */	BAD_CHAR,  	
/* U+0243 */	BAD_CHAR,  	
/* U+0244 */	BAD_CHAR,  	
/* U+0245 */	BAD_CHAR,  	
/* U+0246 */	BAD_CHAR,  	
/* U+0247 */	BAD_CHAR,  	
/* U+0248 */	BAD_CHAR,  	
/* U+0249 */	BAD_CHAR,  	
/* U+024A */	BAD_CHAR,  	
/* U+024B */	BAD_CHAR,  	
/* U+024C */	BAD_CHAR,  	
/* U+024D */	BAD_CHAR,  	
/* U+024E */	BAD_CHAR,  	
/* U+024F */	BAD_CHAR,  	
/* U+0250 */	'a',       	/* LATIN SMALL LETTER TURNED A */
/* U+0251 */	'a',       	/* LATIN SMALL LETTER ALPHA */
/* U+0252 */	'a',       	/* LATIN SMALL LETTER TURNED ALPHA */
/* U+0253 */	'b',       	/* LATIN SMALL LETTER B WITH HOOK */
/* U+0254 */	'o',       	/* LATIN SMALL LETTER OPEN O */
/* U+0255 */	'c',       	/* LATIN SMALL LETTER C WITH CURL */
/* U+0256 */	'd',       	/* LATIN SMALL LETTER D WITH TAIL */
/* U+0257 */	'd',       	/* LATIN SMALL LETTER D WITH HOOK */
/* U+0258 */	'e',       	/* LATIN SMALL LETTER REVERSED E */
/* U+0259 */	'e',       	/* LATIN SMALL LETTER SCHWA */
/* U+025A */	'e',       	/* LATIN SMALL LETTER SCHWA WITH HOOK */
/* U+025B */	'e',       	/* LATIN SMALL LETTER OPEN E */
/* U+025C */	'e',       	/* LATIN SMALL LETTER REVERSED OPEN E */
/* U+025D */	'e',       	/* LATIN SMALL LETTER REVERSED OPEN E WITH HOOK */
/* U+025E */	'e',       	/* LATIN SMALL LETTER CLOSED REVERSED OPEN E */
/* U+025F */	'j',       	/* LATIN SMALL LETTER DOTLESS J WITH STROKE */
/* U+0260 */	'g',       	/* LATIN SMALL LETTER G WITH HOOK */
/* U+0261 */	'g',       	/* LATIN SMALL LETTER SCRIPT G */
/* U+0262 */	'G',       	/* LATIN LETTER SMALL CAPITAL G */
/* U+0263 */	'g',       	/* LATIN SMALL LETTER GAMMA */
/* U+0264 */	BAD_CHAR,  	/* LATIN SMALL LETTER RAMS HORN */
/* U+0265 */	'h',       	/* LATIN SMALL LETTER TURNED H */
/* U+0266 */	'h',       	/* LATIN SMALL LETTER H WITH HOOK */
/* U+0267 */	'h',       	/* LATIN SMALL LETTER HENG WITH HOOK */
/* U+0268 */	'i',       	/* LATIN SMALL LETTER I WITH STROKE */
/* U+0269 */	'i',       	/* LATIN SMALL LETTER IOTA */
/* U+026A */	'I',       	/* LATIN LETTER SMALL CAPITAL I */
/* U+026B */	'l',       	/* LATIN SMALL LETTER L WITH MIDDLE TILDE */
/* U+026C */	'l',       	/* LATIN SMALL LETTER L WITH BELT */
/* U+026D */	'l',       	/* LATIN SMALL LETTER L WITH RETROFLEX HOOK */
/* U+026E */	BAD_CHAR,  	/* LATIN SMALL LETTER LEZH */
/* U+026F */	'm',       	/* LATIN SMALL LETTER TURNED M */
/* U+0270 */	'm',       	/* LATIN SMALL LETTER TURNED M WITH LONG LEG */
/* U+0271 */	'm',       	/* LATIN SMALL LETTER M WITH HOOK */
/* U+0272 */	'n',       	/* LATIN SMALL LETTER N WITH LEFT HOOK */
/* U+0273 */	'n',       	/* LATIN SMALL LETTER N WITH RETROFLEX HOOK */
/* U+0274 */	'N',       	/* LATIN LETTER SMALL CAPITAL N */
/* U+0275 */	'o',       	/* LATIN SMALL LETTER BARRED O */
/* U+0276 */	BAD_CHAR,  	/* LATIN LETTER SMALL CAPITAL OE */
/* U+0277 */	BAD_CHAR,  	/* LATIN SMALL LETTER CLOSED OMEGA */
/* U+0278 */	BAD_CHAR,  	/* LATIN SMALL LETTER PHI */
/* U+0279 */	'r',       	/* LATIN SMALL LETTER TURNED R */
/* U+027A */	'r',       	/* LATIN SMALL LETTER TURNED R WITH LONG LEG */
/* U+027B */	'r',       	/* LATIN SMALL LETTER TURNED R WITH HOOK */
/* U+027C */	'r',       	/* LATIN SMALL LETTER R WITH LONG LEG */
/* U+027D */	'r',       	/* LATIN SMALL LETTER R WITH TAIL */
/* U+027E */	'r',       	/* LATIN SMALL LETTER R WITH FISHHOOK */
/* U+027F */	'r',       	/* LATIN SMALL LETTER REVERSED R WITH FISHHOOK */
/* U+0280 */	'R',       	/* LATIN LETTER SMALL CAPITAL R */
/* U+0281 */	'R',       	/* LATIN LETTER SMALL CAPITAL INVERTED R */
/* U+0282 */	's',       	/* LATIN SMALL LETTER S WITH HOOK */
/* U+0283 */	's',       	/* LATIN SMALL LETTER ESH */
/* U+0284 */	's',       	/* LATIN SMALL LETTER DOTLESS J WITH STROKE AND HOOK */
/* U+0285 */	's',       	/* LATIN SMALL LETTER SQUAT REVERSED ESH */
/* U+0286 */	's',       	/* LATIN SMALL LETTER ESH WITH CURL */
/* U+0287 */	't',       	/* LATIN SMALL LETTER TURNED T */
/* U+0288 */	't',       	/* LATIN SMALL LETTER T WITH RETROFLEX HOOK */
/* U+0289 */	'u',       	/* LATIN SMALL LETTER U BAR */
/* U+028A */	'u',       	/* LATIN SMALL LETTER UPSILON */
/* U+028B */	'v',       	/* LATIN SMALL LETTER V WITH HOOK */
/* U+028C */	'v',       	/* LATIN SMALL LETTER TURNED V */
/* U+028D */	'w',       	/* LATIN SMALL LETTER TURNED W */
/* U+028E */	'y',       	/* LATIN SMALL LETTER TURNED Y */
/* U+028F */	'Y',       	/* LATIN LETTER SMALL CAPITAL Y */
/* U+0290 */	'z',       	/* LATIN SMALL LETTER Z WITH RETROFLEX HOOK */
/* U+0291 */	'z',       	/* LATIN SMALL LETTER Z WITH CURL */
/* U+0292 */	BAD_CHAR,  	/* LATIN SMALL LETTER EZH */
/* U+0293 */	BAD_CHAR,  	/* LATIN SMALL LETTER EZH WITH CURL */
/* U+0294 */	'?',       	/* LATIN LETTER GLOTTAL STOP */
/* U+0295 */	BAD_CHAR,  	/* LATIN LETTER PHARYNGEAL VOICED FRICATIVE */
/* U+0296 */	BAD_CHAR,  	/* LATIN LETTER INVERTED GLOTTAL STOP */
/* U+0297 */	'C',       	/* LATIN LETTER STRETCHED C */
/* U+0298 */	BAD_CHAR,  	/* LATIN LETTER BILABIAL CLICK */
/* U+0299 */	'B',       	/* LATIN LETTER SMALL CAPITAL B */
/* U+029A */	'e',       	/* LATIN SMALL LETTER CLOSED OPEN E */
/* U+029B */	'g',       	/* LATIN LETTER SMALL CAPITAL G WITH HOOK */
/* U+029C */	'H',       	/* LATIN LETTER SMALL CAPITAL H */
/* U+029D */	'j',       	/* LATIN SMALL LETTER J WITH CROSSED-TAIL */
/* U+029E */	'k',       	/* LATIN SMALL LETTER TURNED K */
/* U+029F */	'L',       	/* LATIN LETTER SMALL CAPITAL L */
/* U+02A0 */	'q',       	/* LATIN SMALL LETTER Q WITH HOOK */
/* U+02A1 */	'?',       	/* LATIN LETTER GLOTTAL STOP WITH STROKE */
/* U+02A2 */	BAD_CHAR,  	/* LATIN LETTER REVERSED GLOTTAL STOP WITH STROKE */
/* U+02A3 */	BAD_CHAR,  	/* LATIN SMALL LETTER DZ DIGRAPH */
/* U+02A4 */	BAD_CHAR,  	/* LATIN SMALL LETTER DEZH DIGRAPH */
/* U+02A5 */	BAD_CHAR,  	/* LATIN SMALL LETTER DZ DIGRAPH WITH CURL */
/* U+02A6 */	BAD_CHAR,  	/* LATIN SMALL LETTER TS DIGRAPH */
/* U+02A7 */	BAD_CHAR,  	/* LATIN SMALL LETTER TESH DIGRAPH */
/* U+02A8 */	BAD_CHAR,  	/* LATIN SMALL LETTER TC DIGRAPH WITH CURL */
/* U+02A9 */	BAD_CHAR,  	/* LATIN SMALL LETTER FENG DIGRAPH */
/* U+02AA */	BAD_CHAR,  	/* LATIN SMALL LETTER LS DIGRAPH */
/* U+02AB */	BAD_CHAR,  	/* LATIN SMALL LETTER LZ DIGRAPH */
/* U+02AC */	BAD_CHAR,  	/* LATIN LETTER BILABIAL PERCUSSIVE */
/* U+02AD */	BAD_CHAR,  	/* LATIN LETTER BIDENTAL PERCUSSIVE */
/* U+02AE */	'h',       	/* LATIN SMALL LETTER TURNED H WITH FISHHOOK */
/* U+02AF */	'h',       	/* LATIN SMALL LETTER TURNED H WITH FISHHOOK AND TAIL */
/* U+02B0 */	'h',       	/* MODIFIER LETTER SMALL H */
/* U+02B1 */	'h',       	/* MODIFIER LETTER SMALL H WITH HOOK */
/* U+02B2 */	'j',       	/* MODIFIER LETTER SMALL J */
/* U+02B3 */	'r',       	/* MODIFIER LETTER SMALL R */
/* U+02B4 */	'r',       	/* MODIFIER LETTER SMALL TURNED R */
/* U+02B5 */	'r',       	/* MODIFIER LETTER SMALL TURNED R WITH HOOK */
/* U+02B6 */	'R',       	/* MODIFIER LETTER SMALL CAPITAL INVERTED R */
/* U+02B7 */	'w',       	/* MODIFIER LETTER SMALL W */
/* U+02B8 */	'y',       	/* MODIFIER LETTER SMALL Y */
/* U+02B9 */	'\'',       	/* MODIFIER LETTER PRIME */
/* U+02BA */	'"',       	/* MODIFIER LETTER DOUBLE PRIME */
/* U+02BB */	'`',       	/* MODIFIER LETTER TURNED COMMA */
/* U+02BC */	'\'',       	/* MODIFIER LETTER APOSTROPHE */
/* U+02BD */	'`',       	/* MODIFIER LETTER REVERSED COMMA */
/* U+02BE */	'\'',       	/* MODIFIER LETTER RIGHT HALF RING */
/* U+02BF */	'`',       	/* MODIFIER LETTER LEFT HALF RING */
/* U+02C0 */	BAD_CHAR,  	/* MODIFIER LETTER GLOTTAL STOP */
/* U+02C1 */	BAD_CHAR,  	/* MODIFIER LETTER REVERSED GLOTTAL STOP */
/* U+02C2 */	'<',       	/* MODIFIER LETTER LEFT ARROWHEAD */
/* U+02C3 */	'>',       	/* MODIFIER LETTER RIGHT ARROWHEAD */
/* U+02C4 */	'^',       	/* MODIFIER LETTER UP ARROWHEAD */
/* U+02C5 */	'v',       	/* MODIFIER LETTER DOWN ARROWHEAD */
/* U+02C6 */	'^',       	/* MODIFIER LETTER CIRCUMFLEX ACCENT */
/* U+02C7 */	'v',       	/* CARON */
/* U+02C8 */	BAD_CHAR,  	/* MODIFIER LETTER VERTICAL LINE */
/* U+02C9 */	BAD_CHAR,  	/* MODIFIER LETTER MACRON */
/* U+02CA */	'\'',       	/* MODIFIER LETTER ACUTE ACCENT */
/* U+02CB */	'`',       	/* MODIFIER LETTER GRAVE ACCENT */
/* U+02CC */	BAD_CHAR,  	/* MODIFIER LETTER LOW VERTICAL LINE */
/* U+02CD */	BAD_CHAR,  	/* MODIFIER LETTER LOW MACRON */
/* U+02CE */	BAD_CHAR,  	/* MODIFIER LETTER LOW GRAVE ACCENT */
/* U+02CF */	',',       	/* MODIFIER LETTER LOW ACUTE ACCENT */
/* U+02D0 */	BAD_CHAR,  	/* MODIFIER LETTER TRIANGULAR COLON */
/* U+02D1 */	BAD_CHAR,  	/* MODIFIER LETTER HALF TRIANGULAR COLON */
/* U+02D2 */	BAD_CHAR,  	/* MODIFIER LETTER CENTRED RIGHT HALF RING */
/* U+02D3 */	BAD_CHAR,  	/* MODIFIER LETTER CENTRED LEFT HALF RING */
/* U+02D4 */	BAD_CHAR,  	/* MODIFIER LETTER UP TACK */
/* U+02D5 */	BAD_CHAR,  	/* MODIFIER LETTER DOWN TACK */
/* U+02D6 */	'+',       	/* MODIFIER LETTER PLUS SIGN */
/* U+02D7 */	'-',       	/* MODIFIER LETTER MINUS SIGN */
/* U+02D8 */	BAD_CHAR,  	/* BREVE */
/* U+02D9 */	BAD_CHAR,  	/* DOT ABOVE */
/* U+02DA */	BAD_CHAR,  	/* RING ABOVE */
/* U+02DB */	BAD_CHAR,  	/* OGONEK */
/* U+02DC */	'~',       	/* SMALL TILDE */
/* U+02DD */	'"',       	/* DOUBLE ACUTE ACCENT */
/* U+02DE */	'`',       	/* MODIFIER LETTER RHOTIC HOOK */
/* U+02DF */	'\'',       	/* MODIFIER LETTER CROSS ACCENT */
/* U+02E0 */	BAD_CHAR,  	/* MODIFIER LETTER SMALL GAMMA */
/* U+02E1 */	BAD_CHAR,  	/* MODIFIER LETTER SMALL L */
/* U+02E2 */	BAD_CHAR,  	/* MODIFIER LETTER SMALL S */
/* U+02E3 */	BAD_CHAR,  	/* MODIFIER LETTER SMALL X */
/* U+02E4 */	BAD_CHAR,  	/* MODIFIER LETTER SMALL REVERSED GLOTTAL STOP */
/* U+02E5 */	BAD_CHAR,  	/* MODIFIER LETTER EXTRA-HIGH TONE BAR */
/* U+02E6 */	BAD_CHAR,  	/* MODIFIER LETTER HIGH TONE BAR */
/* U+02E7 */	BAD_CHAR,  	/* MODIFIER LETTER MID TONE BAR */
/* U+02E8 */	BAD_CHAR,  	/* MODIFIER LETTER LOW TONE BAR */
/* U+02E9 */	BAD_CHAR,  	/* MODIFIER LETTER EXTRA-LOW TONE BAR */
/* U+02EA */	BAD_CHAR,  	/* MODIFIER LETTER YIN DEPARTING TONE MARK */
/* U+02EB */	BAD_CHAR,  	/* MODIFIER LETTER YANG DEPARTING TONE MARK */
/* U+02EC */	BAD_CHAR,  	/* MODIFIER LETTER VOICING */
/* U+02ED */	BAD_CHAR,  	/* MODIFIER LETTER UNASPIRATED */
/* U+02EE */	'"',       	/* MODIFIER LETTER DOUBLE APOSTROPHE */
};
