#!/usr/bin/env perl
use warnings;

while(<>)
{
    chomp;
    s/^#.*//;
    s/\\b/\b/g;
    s/\\n/\n/g;
    s/\\e/\e/g;
    s/\\a/\a/g;
    s/\\f/\f/g;
    s/\\0/\0/g;
    s/\\x([0-9a-fA-F]{2})/sprintf('%c',hex "$1")/ge;
    s/\\\\/\\/g;
    print;
}
